   
<ContentNavigationDrawer>:
    MDBoxLayout:
        orientation: "vertical"
        MDCard:
            MDLabel:
                text: "Langoo"
                font_style: "H4"
                halign: "center"
                valign: "center"
                theme_text_color: "Secondary"
        ScrollView:
            MDList:
                OneLineAvatarIconListItem:
                    text: "Translate"
                    font_style: "Subtitle2"
                    divider_color: [1,1,1,0]
                    on_press: 
                    IconLeftWidget:
                        icon: "translate"
            
                OneLineAvatarIconListItem:
                    text: "Dictionary"
                    font_style: "Subtitle2"
                    divider_color: [1,1,1,0]
                    IconLeftWidget:
                        icon: ""

                OneLineAvatarIconListItem:
                    text: "Settings"
                    font_style: "Subtitle2"
                    divider_color: [1,1,1,0]
                    on_press: app.callback()
                    IconLeftWidget:
                        icon: "cog-outline"


Screen:
    MDNavigationLayout:
        ScreenManager:
            id: screen_manager
            Screen:
                
                name: "Mainscreen"
                MDBoxLayout:
                    orientation: "vertical"


                    MDBottomAppBar:
                        MDToolbar:
                            title: "Tool bar"
                            left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
                            elevation: 10
                            icon: "home"
                            type: "bottom"
                            mode: "end"
            Screen:
                name: "Settingsscreen"
                MDBoxLayout:
                    orientation: "vertical"
                    
                    MDToolbar:
                        title: "Settings"
                        md_bg_color: [1,1,1,1]
                        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
                        opposite_color: 'true'
                        elevation: 5
                        font_style: "Subtitle1"
                    Widget:

        MDNavigationDrawer:
            id: nav_drawer
            ContentNavigationDrawer: